# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0002_join_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='ref_id',
            field=models.CharField(default='XYZ', max_length=120),
        ),
    ]
