# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0004_auto_20170122_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='ref_id',
            field=models.CharField(default='XYZ', max_length=120, unique=True),
        ),
    ]
