# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0007_auto_20170122_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='ip_address',
            field=models.CharField(default='ABC', max_length=120),
        ),
        migrations.AlterField(
            model_name='join',
            name='ref_id',
            field=models.CharField(default='XYZ', max_length=120, unique=True),
        ),
    ]
