# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0011_auto_20170126_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='join',
            old_name='friends',
            new_name='friend',
        ),
    ]
