# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0012_auto_20170126_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='ref_id',
            field=models.CharField(blank=True, default='XYZ', max_length=120, unique=True),
        ),
    ]
